# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

keywords:     # site default keywords
logo:         # logo url
back_to_top: true  # back to top button
avatar:       # avatar url, the default is an spy icon.


# Site menu.
# Be aware that this theme doesn't implement categories, archives, sitemap page.
menu:
  home: /
  tags: /tags
  about: /about
  # categories: /categories
  # archives: /archives 
  # sitemap: /sitemap.xml

# Corresponding to menu.
menu_icons:
  home: home
  about: spy
  categories: grid layout
  schedule: calendar
  tags: tags
  archives: archive
  sitemap: sitemap


# Post meta display settings
post_meta:
  created_at: true
  updated_at: false
  categories: false


# Automatically Excerpt. Not recommand.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enabled: true
  length: 750


# Tag cloud options
tag_cloud:
  min_font: 16
  max_font: 30
  start_color: '#888'
  end_color: '#000'


# Social links
# Key is the link label showing to end users, value is the target link.
social:
  github: '#' # https://github.com/<your name>
  weibo:  '#' # http://weibo.com/u/<your name>
  # wechat: 
  # qq: 
  mail: '#' # mailto:<your email address>
  twitter: '#' # https://twitter.com/<your name>
  # facebook: # https://www.facebook.com/<your name>

# Corresponding to social.
social_icons:
  github: github
  weibo: weibo
  wechat: wechat
  qq: qq
  mail: mail
  twitter: twitter
  facebook: facebook


# Code Highlight theme
# Available value:
#    normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties


# Carnival comments plugin. 
# Change enabled value to true and fill site_id to ues this comments plugin.
# See more information at https://carnivalapp.io/
carnival:
  enabled: false
  site_id: # your site id allocated by carnival. 
  # article_author: ''
  # article_selector: "article"
  # block_selector: ":scope > p, :scope > pre"
  # onNewComment:


# Statics files links.
# jquery & semantic_ui is necessary, katex is optional if you don't need to render LaTex formula.
statics:
  jquery: //cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js
  semantic_ui:
    css: //cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.css
    js: //cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.js
  katex:
    css: //cdnjs.cloudflare.com/ajax/libs/KaTeX/0.7.1/katex.min.css