title:
  archive: Archive
  category: Category
  tag: Tag

menu:
  home: Home
  archives: Archives
  categories: Categories
  tags: Tags
  about: About
  search: Search
  sitemap: Sitemap

post:
  created: Post created
  modified: Post modified
  sticky: Sticky
  posted: Posted on
  in: In
  read_more: Read more
  untitled: Untitled
  toc_empty: This post does not have a Table of Contents
  visitors: Visitors

counter:
  tag_cloud:
    zero: No tags
    one: 1 tag in total
    other: "%d tags in total"
    